# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Audio Capture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
pod 'Alamofire', '~> 4.5'
pod 'Alamofire-SwiftyJSON'
  use_frameworks!

  # Pods for Audio Capture

  target 'Audio CaptureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Audio CaptureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
